name: Build Docker Image
description: Build Docker Image Action

outputs:
  image_name:
    description: Name of the built Docker image
    value: ${{ steps.post-build.outputs.image_name }}

runs:
  using: "composite"
  steps:
    # Checkout ar-image repository to get the Dockerfile
    - name: Checkout ar-image repo for Dockerfile
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: Audioreach/ar-image

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Pre-Build Docker Image
      id: pre-build
      shell: bash
      run: |
        uid=$(id -u)
        gid=$(id -g)
        user=$(whoami)
        echo "uid=$uid" >> "$GITHUB_OUTPUT"
        echo "gid=$gid" >> "$GITHUB_OUTPUT"
        echo "user=$user" >> "$GITHUB_OUTPUT"
        echo "Running as user: $user (UID: $uid, GID: $gid)"

    - name: Build Docker Image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: ar-image:latest
        build-args: |
          "USER=${{ steps.pre-build.outputs.user }}"
          "UID=${{ steps.pre-build.outputs.uid }}"
          "GID=${{ steps.pre-build.outputs.gid }}"
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Post-Build Docker Image
      id: post-build
      shell: bash
      run: |
        echo "Docker image ar-image:latest built successfully."
        echo "image_name=ar-image:latest" >> "$GITHUB_OUTPUT"

    # Checkout the main repo again for later steps
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
