name: Build Docker Image
description: Build Docker Image Action
 
outputs:
  image_name:
    description: Name of the built Docker image
    value: ${{ steps.build.outputs.image_name }}
 
runs:
  using: "composite"
  steps:
    - name: Checkout ar-image repo for Dockerfile
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: Audioreach/ar-image
 
    - name: Build Docker Image
      shell: bash
      id: build
      run: |
        echo "::group::$(printf '__________ %-100s' 'build' | tr ' ' _)"
        docker build -t ar-image:latest --build-arg "USER=$(whoami)" --build-arg "UID=$(id -u)" --build-arg "GID=$(id -g)" -f Dockerfile .
        echo "::endgroup::"
        echo "Docker image ar-image:latest built successfully."
        echo "image_name=ar-image:latest" >> $GITHUB_OUTPUT
        echo "Docker image name: ar-image:latest" >> $GITHUB_STEP_SUMMARY
 
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
