---
name: _build
description: Reusable workflow for build instructions

on:
  workflow_call:
    inputs:
      build_args:
        required: true
        type: string
        description: Required build arguments

# Use Kodiak's sdk for compiling, as sdk is similar for all the targets
env:
  SDK_NAME: poky-glibc-x86_64-core-image-base-armv8-2a-qcs6490-rb3gen2-core-kit-toolchain-5.2.sh


jobs:
  build:
    runs-on:
      group: GHA-Audioreach-SelfHosted-RG
      labels: [ self-hosted, audior-prd-u2204-x64-large-od-ephem ]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Build docker Image
        id: get-docker-image
        uses: ./.github/actions/build_docker_image

      - name: Pull SDK sh file
        id: pull_sdk
        uses: ./.github/actions/aws-s3-exchanger
        with:
          s3_bucket: qli-prd-audior-gh-artifacts
          download_filename: ${{ env.SDK_NAME }}
          mode: download
          location: Audioreach/meta-ar/post_merge_build

      - name: Setup Directory Structure
        run: mkdir -p install/tmp

      - name: Run SDK Script
        id: run_sdk
        shell: bash
        run: |
          echo "Running SDK Script"
          echo "./install" | ./${{ env.SDK_NAME }}
          echo "SDK Script ran successfully"

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          docker_image: ${{ steps.get-docker-image.outputs.image_name }}
        env:
          BUILD_ARGS: ${{ inputs.build_args }}

      - name: Clean Up Workspace
        if: always() 
        shell: bash
        run: |
          echo "Cleaning Up Workspace"
          rm -rf install/ ${{ env.SDK_NAME }}
          rm -rf build/ ${{ github.workspace }}/build.tar
          echo "Workspace cleaned up successfully"
