---
name: _loading
description: Load required parameters for the subsequent jobs

on:
  workflow_call:
    outputs:
      build_args:
        description: The build arguments
        value: ${{ jobs.loading.outputs.build_args }}

jobs:
  loading:
    runs-on: ubuntu-latest
    outputs:
      build_args: ${{ steps.loading.outputs.build_args }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Load Parameters
        id: loading
        uses: ./.github/actions/loading
