---
name: pre_merge_build
run-name: Pre Merge Build ${{ github.event.pull_request.number }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  load_parameters:
    uses: ./.github/workflows/loading.yml

  build:
    needs: load_parameters
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_args: ${{ needs.load_parameters.outputs.build_args }}

  process_image:
    needs: [ load_parameters, build ]
    uses: ./.github/workflows/process_image.yml
    secrets: inherit
    with:
      docker_image: ar-image:latest

  trigger_lava:
    needs: [ load_parameters, build, process_image ]
    uses: ./.github/workflows/test.yml
    secrets: inherit
